#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: checkstyle

# File Options
files:
  include: '*.s+(a|c)ss'
# Rule Configuration
rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1
  mixins-before-declarations:
    - 1
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 1
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 1
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 1
    -
      properties:
        - margin
        - content